/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.ListModel;
import util.Resource;
import util.Score;
import util.ScoreManager;

/**
 *
 * @author michele.tomyslak
 */
public class HighScoresPanel extends javax.swing.JPanel {

    private ScoreManager scoreManager;
    
    /**
     * Creates new form HighScoresPanel
     */
    public HighScoresPanel() {
        initComponents();
        scoreManager = new ScoreManager("data/Scores.csv");
        this.setSize(new Dimension(400,400));
        
        
    }
    
    @Override
    public void paintComponent(Graphics g){
        
        g.setColor(Color.WHITE);
        int counter = 0;
        for (Score s :scoreManager.getScores()) {
            //System.out.println(" 2");
            g.drawString(s.getName()+","+s.getScoredPoints(), 50, counter*50);
            counter++;
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
}
